// chapter-18/angularapp/src/app/categoryList.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
    selector: "category-list",
    templateUrl: "./categoryList.component.html"
})
export class CategegoryList {

    @Input()
    selected: string = ""

    @Input()
    categories: string[] = [];

    @Output()
    selectCategory = new EventEmitter<string>();

    getBtnClass(category: string): string {
        return "btn btn-block " + (category === this.selected ? "btn-primary" : "btn-secondary");
    }
}

// chapter-20/reactapp/src/categoryList.tsx
import React, { FunctionComponent } from "react";

interface Props {
    selected: string,
    categories: string[],
    selectCategory: (category: string) => void;
}

export const CategoryList: FunctionComponent<Props> = (props) => {
    return <div className="d-grid gap-2">
        {["All", ...props.categories].map(c => {
            let btnClass = props.selected === c ? "btn-primary" : "btn-secondary";
            return <button key={c} className={`btn btn-block ${btnClass}`} onClick={() => props.selectCategory(c)}>
                {c}
            </button>
        })}
    </div>
}
