// chapter-21/reactapp/src/productList.tsx
import React, { FunctionComponent, useState } from "react";
import { Header } from "./header";
import { ProductItem } from "./productItem";
import { CategoryList } from "./categoryList";
import { Product, ProductSelection } from "./data/entities";

interface Props {
    products: Product[],
    categories: string[],
    selections: ProductSelection[],
    addToOrder: (product: Product, quantity: number) => void
}

export const ProductList: FunctionComponent<Props> = (props) => {
    const [selectedCategory, setSelectedCategory] = useState("All");

    const products = props.products.filter(p => selectedCategory === "All" || p.category === selectedCategory);

    return <div>
        <Header selections={props.selections} />
        <div className="container-fluid">
            <div className="row">
                <div className="col-3 p-2">
                    <CategoryList categories={props.categories} selected={selectedCategory} selectCategory={setSelectedCategory} />
                </div>
                <div className="col-9 p-2">
                    {
                        products.map(p =>
                            <ProductItem key={p.id} product={p} callback={props.addToOrder} />)
                    }
                </div>
            </div>
        </div>
    </div>
}

// chapter-19/angularapp/src/app/productList.component.ts
import { Component } from "@angular/core";
import { DataSource } from './data/dataSource';
import { Product } from './data/entities';
import { Router } from "@angular/router";

@Component({
    selector: "product-list",
    templateUrl: "./productList.component.html"
})
export class ProductList {
    selectedCategory = "All";

    constructor(public dataSource: DataSource, private router: Router) { }

    get products(): Product[] {
        return this.dataSource.getProducts("id", this.selectedCategory === "All" ? undefined : this.selectedCategory);
    }

    get categories(): string[] {
        return ["All", ...this.dataSource.getCategories()];
    }

    handleCategorySelect(category: string) {
        this.selectedCategory = category;
    }

    handleAdd(data: { product: Product, quantity: number }) {
        this.dataSource.order.addProduct(data.product, data.quantity);
    }

    handleSubmit() {
        this.router.navigateByUrl("/order");
    }
}

<header [order]="dataSource.order" (submit)="handleSubmit()"></header>
<div class="container-fluid">
    <div class="row">
        <div class="col-3 p-2">
            <category-list [selected]="selectedCategory" [categories]="categories"
                (selectCategory)="handleCategorySelect($event)">
            </category-list>
        </div>
        <div class="col-9 p-2">
            <product-item *ngFor="let p of products" [product]="p" (addToCart)="handleAdd($event)"></product-item>
        </div>
    </div>
</div>
