// chapter-19/angularapp/src/app/header.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Order } from './data/entities';

@Component({
    selector: "header",
    templateUrl: "./header.component.html"
})
export class Header {

    @Input()
    order = new Order();

    @Output()
    submit = new EventEmitter<void>();

    get headerText(): string {
        let count = this.order.productCount;
        return count === 0 ? "(No Selection)" : `${count} product(s), $${this.order.total.toFixed(2)}`
    }
}

// chapter-21/reactapp/src/header.tsx
import React, { FunctionComponent } from "react";
import { ProductSelection, ProductSelectionHelpers } from "./data/entities";
import { NavLink } from "react-router-dom";

interface Props {
    selections: ProductSelection[]
}

export const Header: FunctionComponent<Props> = (props) => {
    const count = ProductSelectionHelpers.productCount(props.selections);
    const total = ProductSelectionHelpers.total(props.selections);
    return <div className="p-1 bg-secondary text-white text-end">
        {count === 0 ? "(No Selection)" : `${count} product(s), $${total.toFixed(2)}`}
        {count > 0 ?
            <NavLink to="/order" className="btn btn-sm btn-primary m-1">
                Submit Order
            </NavLink>
            : <button disabled className="btn btn-sm btn-primary m-1">
                Submit Order
            </button>
        }
    </div>
}
