// chapter-20/reactapp/src/productItem.tsx
import React, { Component, ChangeEvent } from "react";
import { Product } from "./data/entities";

interface Props {
    product: Product,
    callback: (product: Product, quantity: number) => void
}

interface State {
    quantity: number
}

export class ProductItem extends Component<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            quantity: 1
        }
    }

    render() {
        return <div className="card m-1 p-1 bg-light">
            <h4>
                {this.props.product.name}
                <span className="badge rounded-pill bg-primary float-end">
                    ${this.props.product.price.toFixed(2)}
                </span>
            </h4>
            <div className="card-text bg-white p-1">
                {this.props.product.description}
                <button className="btn btn-success btn-sm float-end" onClick={this.handleAddToCart} >
                    Add To Cart
                </button>
                <select className="form-control-inline float-end m-1" onChange={this.handleQuantityChange}>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                </select>
            </div>
        </div>
    }

    handleQuantityChange = (ev: ChangeEvent<HTMLSelectElement>): void =>
        this.setState({ quantity: Number(ev.target.value) });

    handleAddToCart = (): void =>
        this.props.callback(this.props.product, this.state.quantity);
}

// chapter-18/angularapp/src/app/productItem.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Product } from './data/entities';

export type productSelection = {
    product: Product,
    quantity: number
}

@Component({
    selector: "product-item",
    templateUrl: "./productItem.component.html"
})
export class ProductItem {
    quantity: number = 1;

    @Input()
    product: Product = {
        id: 0, name: "", description: "", category: "", price: 0
    }

    @Output()
    addToCart = new EventEmitter<productSelection>();
    handleAddToCart() {
        this.addToCart.emit({
            product: this.product,
            quantity: Number(this.quantity)
        });
    }
}

<div class="card m-1 p-1 bg-light">
    <h4>
        {{ product.name }}
        <span class="badge rounded-pill bg-primary float-end">
            ${{ product.price.toFixed(2) }}
        </span>
    </h4>
    <div class="card-text bg-white p-1">
        {{ product.description }}
        <button class="btn btn-success btn-sm float-end" (click)="handleAddToCart()">
            Add To Cart
        </button>
        <select class="form-control-inline float-end m-1" [(ngModel)]="quantity">
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
    </div>
</div>
